[package]
name = "purelisp"
version = "0.1.0"
edition = "2024"

[build-dependencies]
lalrpop = "0.22.1"

[dependencies]
rustyline = "15.0.0"
regex = "1.11.1"
lalrpop-util = { version = "0.21.0", features = ["lexer", "unicode"] }
